### ISSUE TITLE
singularity installation fails on aws runner

### ISSUE THREAD

**Issue by hvgazula** [hvgazula/trained-models#9]
Now where did this come from? :) @gaiborjosue 

https://github.com/hvgazula/trained-models/actions/runs/6792345716

**Comment by gaiborjosue** [comment]
If it is following the regular installation process it shouldn't fail on installation. Could you please try again?

**Comment by hvgazula** [comment]
failed again..wow this is very curious...could you try the same workflow on your end before our meeting tmrw morning?

**Comment by gaiborjosue** [comment]
Did you remove the step of installing python above installing singularity? That is the only difference I can find with my workflow:

![image](https://github.com/hvgazula/trained-models/assets/78832141/67563f2e-6234-4bc0-bafc-ec7bea44cd36)

**Comment by hvgazula** [comment]
Yep.. tried both with and without 😁

**Comment by hvgazula** [comment]
changing values of all aws-related environmental variables resolved it..
